### ISSUE TITLE
This for HTML?

### ISSUE THREAD

**Issue by sbrl** [expandoco/expando-atom#3]
This looks awesome. Is there a package that does this for HTML too?

**Comment by faniereynders** [comment]
You could look at http://emmet.io

**Comment by sbrl** [comment]
Yeah, but emmet comes with a bunch of extra stuff I don't want / need.

**Comment by faniereynders** [comment]
you could implement your own formatter for HTML. Do you mean output data in HTML as a table object?

**Comment by sbrl** [comment]
Yeah, I mean a shorthand for generating html. e.g. something like `div#someid>div.somecontainer*3>strong>[text here]` would result in something like

``` html
<div id="someid">
  <div class="somecontainer"><strong>text here</strong></div>
  <div class="somecontainer"><strong>text here</strong></div>
  <div class="somecontainer"><strong>text here</strong></div>
</div>
```

I might actually write a quick engine that does just that. I don't know how I'd bundle it into an atom package though.

**Comment by faniereynders** [comment]
I would still recommend emmet for this. Expando focuses on creating data in
specific formats from a set syntax. Please see the expando-core repo

**Comment by sbrl** [comment]
I don't get what expando-core is, but I'll have to take a look at creating my own package at some point.

**Comment by faniereynders** [comment]
expando core is the core library containing all the types, formatters and parsers that transforms the shorthand text into desired data. This is used within platform specific packages like expando-atom and expando-vs code which are the actual extensions of Atom and VS Code

**Comment by sbrl** [comment]
Ah cool :-)
